# Generated by Django 3.0.8 on 2020-07-29 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200728_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
