# Generated by Django 3.0.8 on 2020-07-30 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200730_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateField(),
        ),
    ]
