# Generated by Django 3.0.8 on 2020-07-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200721_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
